export const FAMILIES = {
  "OpenAI — GPT Series": [
    {
      model: "GPT-3.5 Turbo",
      size: "~20B (est.)",
      ctx: "16K",
      date: "2023-03-01",
      tier: "frontier",
    },
    {
      model: "GPT-4",
      size: "~1.7T (est., MoE)",
      ctx: "8K/32K",
      date: "2023-03-14",
      tier: "frontier",
    },
    {
      model: "GPT-4 Turbo",
      size: "~1.7T (est.)",
      ctx: "128K",
      date: "2023-11-06",
      tier: "frontier",
    },
    {
      model: "GPT-4o",
      size: "~200B (est.)",
      ctx: "128K",
      date: "2024-05-13",
      tier: "frontier",
    },
    {
      model: "GPT-4o mini",
      size: "~8B (est.)",
      ctx: "128K",
      date: "2024-07-18",
      tier: "efficient",
    },
    {
      model: "GPT-4.5",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-02-28",
      tier: "frontier",
    },
    {
      model: "GPT-4.1",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-04-14",
      tier: "frontier",
    },
    {
      model: "GPT-4.1 mini",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-04-14",
      tier: "efficient",
    },
    {
      model: "GPT-4.1 nano",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-04-14",
      tier: "nano",
    },
    {
      model: "GPT-5",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-08-07",
      tier: "frontier",
    },
    {
      model: "GPT-5.1 Codex-Max",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-11-20",
      tier: "coding-agent",
    },
    {
      model: "GPT-5.2",
      size: "Undisclosed",
      ctx: "512K",
      date: "2025-12-13",
      tier: "frontier",
    },
    {
      model: "GPT-5.2-Codex",
      size: "Undisclosed",
      ctx: "512K",
      date: "2025-12-19",
      tier: "coding-agent",
    },
    {
      model: "GPT-5.4",
      size: "Undisclosed",
      ctx: "1M",
      date: "2026-03-06",
      tier: "frontier",
    },
  ],
  "OpenAI — o-series (Reasoning)": [
    {
      model: "o1-preview",
      size: "Undisclosed",
      ctx: "128K",
      date: "2024-09-12",
      tier: "reasoning",
    },
    {
      model: "o1-mini",
      size: "Undisclosed",
      ctx: "128K",
      date: "2024-09-12",
      tier: "reasoning-efficient",
    },
    {
      model: "o1",
      size: "Undisclosed",
      ctx: "200K",
      date: "2024-12-05",
      tier: "reasoning",
    },
    {
      model: "o1 pro",
      size: "Undisclosed",
      ctx: "200K",
      date: "2024-12-05",
      tier: "reasoning",
    },
    {
      model: "o3-mini",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-02-17",
      tier: "reasoning-efficient",
    },
    {
      model: "o3",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-04-16",
      tier: "reasoning",
    },
    {
      model: "o3-pro",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-06-10",
      tier: "reasoning",
    },
    {
      model: "o4-mini",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-04-16",
      tier: "reasoning-efficient",
    },
  ],
  "OpenAI — Media": [
    {
      model: "Sora",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-12-09",
      tier: "video",
    },
    {
      model: "Sora 2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-10-01",
      tier: "video",
    },
    {
      model: "DALL-E 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2023-10-01",
      tier: "image",
    },
    {
      model: "Whisper Large v3",
      size: "1.5B",
      ctx: "N/A",
      date: "2023-11-01",
      tier: "audio",
    },
  ],
  "Anthropic — Claude 3 Family": [
    {
      model: "Claude 3 Haiku",
      size: "~20B (est.)",
      ctx: "200K",
      date: "2024-03-04",
      tier: "efficient",
    },
    {
      model: "Claude 3 Sonnet",
      size: "~70B (est.)",
      ctx: "200K",
      date: "2024-03-04",
      tier: "balanced",
    },
    {
      model: "Claude 3 Opus",
      size: "~137B (est.)",
      ctx: "200K",
      date: "2024-03-04",
      tier: "frontier",
    },
  ],
  "Anthropic — Claude 3.5 Family": [
    {
      model: "Claude 3.5 Sonnet (v1)",
      size: "Undisclosed",
      ctx: "200K",
      date: "2024-06-20",
      tier: "frontier",
    },
    {
      model: "Claude 3.5 Sonnet (v2)",
      size: "Undisclosed",
      ctx: "200K",
      date: "2024-10-22",
      tier: "frontier",
    },
    {
      model: "Claude 3.5 Haiku",
      size: "Undisclosed",
      ctx: "200K",
      date: "2024-11-04",
      tier: "efficient",
    },
  ],
  "Anthropic — Claude 3.7+": [
    {
      model: "Claude 3.7 Sonnet",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-02-24",
      tier: "frontier",
    },
    {
      model: "Claude 4 Sonnet",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-05-22",
      tier: "frontier",
    },
    {
      model: "Claude 4 Opus",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-05-22",
      tier: "frontier",
    },
    {
      model: "Claude 4.5",
      size: "Undisclosed",
      ctx: "200K",
      date: "2025-09-22",
      tier: "frontier",
    },
    {
      model: "Claude Opus 4.6",
      size: "Undisclosed",
      ctx: "1M",
      date: "2026-02-06",
      tier: "frontier",
    },
    {
      model: "Claude Sonnet 4.6",
      size: "Undisclosed",
      ctx: "1M",
      date: "2026-02-18",
      tier: "balanced",
    },
  ],
  "Google — Gemini": [
    {
      model: "Gemini 1.0 Pro",
      size: "Undisclosed",
      ctx: "32K",
      date: "2023-12-06",
      tier: "frontier",
    },
    {
      model: "Gemini 1.0 Ultra",
      size: "Undisclosed",
      ctx: "32K",
      date: "2024-02-08",
      tier: "frontier",
    },
    {
      model: "Gemini 1.5 Pro",
      size: "Undisclosed (~340B est.)",
      ctx: "1M",
      date: "2024-05-14",
      tier: "frontier",
    },
    {
      model: "Gemini 1.5 Flash",
      size: "Undisclosed (~70B est.)",
      ctx: "1M",
      date: "2024-05-14",
      tier: "efficient",
    },
    {
      model: "Gemini 1.5 Flash-8B",
      size: "8B",
      ctx: "1M",
      date: "2024-10-03",
      tier: "nano",
    },
    {
      model: "Gemini 2.0 Flash",
      size: "Undisclosed",
      ctx: "1M",
      date: "2024-12-11",
      tier: "efficient",
    },
    {
      model: "Gemini 2.0 Flash-Lite",
      size: "Undisclosed",
      ctx: "1M",
      date: "2024-12-11",
      tier: "nano",
    },
    {
      model: "Gemini 2.5 Pro",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-03-25",
      tier: "frontier",
    },
    {
      model: "Gemini 2.5 Flash",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-04-17",
      tier: "efficient",
    },
    {
      model: "Gemini 2.5 Flash Lite",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-06-17",
      tier: "nano",
    },
    {
      model: "Gemini 3 Pro",
      size: "Undisclosed",
      ctx: "2M",
      date: "2025-11-19",
      tier: "frontier",
    },
    {
      model: "Gemini 3 Deep Think",
      size: "Undisclosed",
      ctx: "2M",
      date: "2025-12-04",
      tier: "reasoning",
    },
    {
      model: "Gemini 3 Flash",
      size: "Undisclosed",
      ctx: "2M",
      date: "2025-12-17",
      tier: "efficient",
    },
    {
      model: "Gemini 3.1 Pro",
      size: "Undisclosed",
      ctx: "2M",
      date: "2026-02-19",
      tier: "frontier",
    },
    {
      model: "Gemini 3.1 Flash-Lite",
      size: "Undisclosed",
      ctx: "1M",
      date: "2026-03-04",
      tier: "nano",
    },
  ],
  "Google — Gemma (Open-Source)": [
    {
      model: "Gemma 2B",
      size: "2B",
      ctx: "8K",
      date: "2024-02-21",
      tier: "open-source",
    },
    {
      model: "Gemma 7B",
      size: "7B",
      ctx: "8K",
      date: "2024-02-21",
      tier: "open-source",
    },
    {
      model: "Gemma 2 2B",
      size: "2B",
      ctx: "8K",
      date: "2024-06-27",
      tier: "open-source",
    },
    {
      model: "Gemma 2 9B",
      size: "9B",
      ctx: "8K",
      date: "2024-06-27",
      tier: "open-source",
    },
    {
      model: "Gemma 2 27B",
      size: "27B",
      ctx: "8K",
      date: "2024-06-27",
      tier: "open-source",
    },
    {
      model: "Gemma 3 1B",
      size: "1B",
      ctx: "128K",
      date: "2025-03-12",
      tier: "open-source",
    },
    {
      model: "Gemma 3 4B",
      size: "4B",
      ctx: "128K",
      date: "2025-03-12",
      tier: "open-source",
    },
    {
      model: "Gemma 3 12B",
      size: "12B",
      ctx: "128K",
      date: "2025-03-12",
      tier: "open-source",
    },
    {
      model: "Gemma 3 27B",
      size: "27B",
      ctx: "128K",
      date: "2025-03-12",
      tier: "open-source",
    },
    {
      model: "Gemma 3n E2B",
      size: "2B effective",
      ctx: "32K",
      date: "2025-05-20",
      tier: "edge",
    },
    {
      model: "Gemma 3n E4B",
      size: "4B effective",
      ctx: "32K",
      date: "2025-05-20",
      tier: "edge",
    },
    {
      model: "VaultGemma",
      size: "Unknown",
      ctx: "128K",
      date: "2025-09-15",
      tier: "privacy",
    },
  ],
  "Google — Media & Science": [
    {
      model: "Imagen 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-05-14",
      tier: "image",
    },
    {
      model: "Veo 2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-12-16",
      tier: "video",
    },
    {
      model: "Veo 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-05-20",
      tier: "video",
    },
    {
      model: "MedGemma 4B",
      size: "4B",
      ctx: "8K",
      date: "2026-01-14",
      tier: "medical",
    },
    {
      model: "AlphaFold 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-05-08",
      tier: "science",
    },
  ],
  "Meta — Llama 3 Family": [
    {
      model: "Llama 3 8B",
      size: "8B",
      ctx: "8K",
      date: "2024-04-18",
      tier: "open-source",
    },
    {
      model: "Llama 3 70B",
      size: "70B",
      ctx: "8K",
      date: "2024-04-18",
      tier: "open-source",
    },
    {
      model: "Llama 3.1 8B",
      size: "8B",
      ctx: "128K",
      date: "2024-07-23",
      tier: "open-source",
    },
    {
      model: "Llama 3.1 70B",
      size: "70B",
      ctx: "128K",
      date: "2024-07-23",
      tier: "open-source",
    },
    {
      model: "Llama 3.1 405B",
      size: "405B",
      ctx: "128K",
      date: "2024-07-23",
      tier: "open-source",
    },
    {
      model: "Llama 3.2 1B",
      size: "1B",
      ctx: "128K",
      date: "2024-09-25",
      tier: "nano",
    },
    {
      model: "Llama 3.2 3B",
      size: "3B",
      ctx: "128K",
      date: "2024-09-25",
      tier: "efficient",
    },
    {
      model: "Llama 3.2 11B Vision",
      size: "11B",
      ctx: "128K",
      date: "2024-09-25",
      tier: "multimodal",
    },
    {
      model: "Llama 3.2 90B Vision",
      size: "90B",
      ctx: "128K",
      date: "2024-09-25",
      tier: "multimodal",
    },
    {
      model: "Llama 3.3 70B",
      size: "70B",
      ctx: "128K",
      date: "2024-12-06",
      tier: "open-source",
    },
  ],
  "Meta — Llama 4 Family": [
    {
      model: "Llama 4 Scout",
      size: "~109B (17B active, MoE 16x)",
      ctx: "10M",
      date: "2025-04-05",
      tier: "open-source",
    },
    {
      model: "Llama 4 Maverick",
      size: "~400B (17B active, MoE)",
      ctx: "10M",
      date: "2025-04-05",
      tier: "open-source",
    },
    {
      model: "Llama 4 Behemoth",
      size: "~2T (est.)",
      ctx: "10M",
      date: "2025-04-05",
      tier: "frontier",
    },
  ],
  "Mistral AI — All Models": [
    {
      model: "Mistral 7B",
      size: "7B",
      ctx: "32K",
      date: "2023-09-27",
      tier: "open-source",
    },
    {
      model: "Mixtral 8x7B",
      size: "56B total / 12B active",
      ctx: "32K",
      date: "2023-12-11",
      tier: "open-source",
    },
    {
      model: "Mixtral 8x22B",
      size: "141B total / 39B active",
      ctx: "64K",
      date: "2024-04-10",
      tier: "open-source",
    },
    {
      model: "Mistral Large",
      size: "~123B",
      ctx: "32K",
      date: "2024-02-26",
      tier: "frontier",
    },
    {
      model: "Mistral Large 2",
      size: "~123B",
      ctx: "128K",
      date: "2024-07-24",
      tier: "frontier",
    },
    {
      model: "Codestral",
      size: "22B",
      ctx: "32K",
      date: "2024-05-29",
      tier: "coding",
    },
    {
      model: "Mathstral 7B",
      size: "7B",
      ctx: "32K",
      date: "2024-07-15",
      tier: "math",
    },
    {
      model: "Mistral Nemo 12B",
      size: "12B",
      ctx: "128K",
      date: "2024-07-18",
      tier: "efficient",
    },
    {
      model: "Pixtral 12B",
      size: "12B",
      ctx: "128K",
      date: "2024-09-11",
      tier: "multimodal",
    },
    {
      model: "Ministral 3B",
      size: "3B",
      ctx: "128K",
      date: "2024-10-16",
      tier: "nano",
    },
    {
      model: "Ministral 8B",
      size: "8B",
      ctx: "128K",
      date: "2024-10-16",
      tier: "efficient",
    },
    {
      model: "Pixtral Large 124B",
      size: "124B",
      ctx: "128K",
      date: "2024-11-12",
      tier: "multimodal",
    },
    {
      model: "Mistral Small 3",
      size: "24B",
      ctx: "32K",
      date: "2025-01-30",
      tier: "efficient",
    },
    {
      model: "Mistral Saba",
      size: "24B",
      ctx: "32K",
      date: "2025-02-17",
      tier: "multilingual",
    },
    {
      model: "Mistral Small 3.1",
      size: "24B",
      ctx: "128K",
      date: "2025-03-17",
      tier: "multimodal",
    },
    {
      model: "Mistral Medium 3",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-05-07",
      tier: "balanced",
    },
    {
      model: "Devstral Small 1.1",
      size: "24B",
      ctx: "128K",
      date: "2025-05-21",
      tier: "coding",
    },
    {
      model: "Codestral 2501",
      size: "22B",
      ctx: "256K",
      date: "2025-01-13",
      tier: "coding",
    },
    {
      model: "Mistral Large 3",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-11-20",
      tier: "frontier",
    },
  ],
  "xAI — Grok": [
    {
      model: "Grok-1",
      size: "314B (MoE)",
      ctx: "8K",
      date: "2023-11-04",
      tier: "frontier",
    },
    {
      model: "Grok-1.5",
      size: "Undisclosed",
      ctx: "128K",
      date: "2024-03-28",
      tier: "frontier",
    },
    {
      model: "Grok-2",
      size: "Undisclosed",
      ctx: "128K",
      date: "2024-08-13",
      tier: "frontier",
    },
    {
      model: "Grok-2 mini",
      size: "Undisclosed",
      ctx: "128K",
      date: "2024-08-13",
      tier: "efficient",
    },
    {
      model: "Grok-2.5",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-07-10",
      tier: "frontier",
    },
    {
      model: "Grok-3",
      size: "~300B (est.)",
      ctx: "128K",
      date: "2025-02-17",
      tier: "frontier",
    },
    {
      model: "Grok-3 mini",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-02-17",
      tier: "efficient",
    },
    {
      model: "Grok-4 Fast",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-09-22",
      tier: "frontier",
    },
    {
      model: "Grok-4.1",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-11-18",
      tier: "frontier",
    },
  ],
  "DeepSeek — All Models": [
    {
      model: "DeepSeek V1",
      size: "67B",
      ctx: "4K",
      date: "2023-11-02",
      tier: "open-source",
    },
    {
      model: "DeepSeek Coder V1",
      size: "7B/33B",
      ctx: "16K",
      date: "2023-11-03",
      tier: "coding",
    },
    {
      model: "DeepSeek V2",
      size: "236B total / 21B active (MoE)",
      ctx: "128K",
      date: "2024-05-07",
      tier: "open-source",
    },
    {
      model: "DeepSeek V2.5",
      size: "236B total / 21B active (MoE)",
      ctx: "128K",
      date: "2024-09-05",
      tier: "open-source",
    },
    {
      model: "DeepSeek Coder V2",
      size: "236B total / 21B active (MoE)",
      ctx: "128K",
      date: "2024-06-17",
      tier: "coding",
    },
    {
      model: "DeepSeek V3",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2024-12-26",
      tier: "open-source",
    },
    {
      model: "DeepSeek R1-Zero",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning",
    },
    {
      model: "DeepSeek R1",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning",
    },
    {
      model: "DeepSeek R1-Distill-7B",
      size: "7B",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning-efficient",
    },
    {
      model: "DeepSeek R1-Distill-14B",
      size: "14B",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning-efficient",
    },
    {
      model: "DeepSeek R1-Distill-32B",
      size: "32B",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning-efficient",
    },
    {
      model: "DeepSeek R1-Distill-70B",
      size: "70B",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning-efficient",
    },
    {
      model: "DeepSeek Janus",
      size: "7B",
      ctx: "8K",
      date: "2024-10-17",
      tier: "multimodal",
    },
    {
      model: "DeepSeek Janus-Pro",
      size: "7B",
      ctx: "8K",
      date: "2025-01-27",
      tier: "multimodal",
    },
    {
      model: "DeepSeek V3 (updated)",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2025-03-24",
      tier: "open-source",
    },
    {
      model: "DeepSeek R1 (updated)",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2025-05-28",
      tier: "reasoning",
    },
    {
      model: "DeepSeek V3.1",
      size: "671B total / 37B active (MoE)",
      ctx: "128K",
      date: "2025-08-20",
      tier: "open-source",
    },
    {
      model: "DeepSeek (math LLM)",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-11-28",
      tier: "math",
    },
  ],
  "Alibaba — Qwen2 Family": [
    {
      model: "Qwen2 0.5B",
      size: "0.5B",
      ctx: "32K",
      date: "2024-06-06",
      tier: "nano",
    },
    {
      model: "Qwen2 1.5B",
      size: "1.5B",
      ctx: "32K",
      date: "2024-06-06",
      tier: "nano",
    },
    {
      model: "Qwen2 7B",
      size: "7B",
      ctx: "128K",
      date: "2024-06-06",
      tier: "open-source",
    },
    {
      model: "Qwen2 57B-A14B",
      size: "57B total / 14B active (MoE)",
      ctx: "64K",
      date: "2024-06-06",
      tier: "open-source",
    },
    {
      model: "Qwen2 72B",
      size: "72B",
      ctx: "128K",
      date: "2024-06-06",
      tier: "open-source",
    },
    {
      model: "Qwen2-VL 2B",
      size: "2B",
      ctx: "32K",
      date: "2024-09-18",
      tier: "multimodal",
    },
    {
      model: "Qwen2-VL 7B",
      size: "7B",
      ctx: "32K",
      date: "2024-09-18",
      tier: "multimodal",
    },
    {
      model: "Qwen2-VL 72B",
      size: "72B",
      ctx: "32K",
      date: "2024-09-18",
      tier: "multimodal",
    },
    {
      model: "Qwen2-Audio",
      size: "7B",
      ctx: "N/A",
      date: "2024-09-18",
      tier: "audio",
    },
  ],
  "Alibaba — Qwen2.5 Family": [
    {
      model: "Qwen2.5 0.5B",
      size: "0.5B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "nano",
    },
    {
      model: "Qwen2.5 1.5B",
      size: "1.5B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "nano",
    },
    {
      model: "Qwen2.5 3B",
      size: "3B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "efficient",
    },
    {
      model: "Qwen2.5 7B",
      size: "7B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "open-source",
    },
    {
      model: "Qwen2.5 14B",
      size: "14B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "open-source",
    },
    {
      model: "Qwen2.5 32B",
      size: "32B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "open-source",
    },
    {
      model: "Qwen2.5 72B",
      size: "72B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "open-source",
    },
    {
      model: "Qwen2.5-Coder 7B",
      size: "7B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "coding",
    },
    {
      model: "Qwen2.5-Coder 32B",
      size: "32B",
      ctx: "128K",
      date: "2024-09-18",
      tier: "coding",
    },
    {
      model: "Qwen2.5-Math 7B",
      size: "7B",
      ctx: "4K",
      date: "2024-09-18",
      tier: "math",
    },
    {
      model: "Qwen2.5-Math 72B",
      size: "72B",
      ctx: "4K",
      date: "2024-09-18",
      tier: "math",
    },
    {
      model: "Qwen2.5-Max",
      size: "Undisclosed (MoE frontier)",
      ctx: "1M",
      date: "2025-01-29",
      tier: "frontier",
    },
    {
      model: "QwQ-32B",
      size: "32B",
      ctx: "128K",
      date: "2025-03-05",
      tier: "reasoning",
    },
    {
      model: "QVQ-72B",
      size: "72B",
      ctx: "32K",
      date: "2024-12-25",
      tier: "reasoning-multimodal",
    },
  ],
  "Alibaba — Qwen3 Family": [
    {
      model: "Qwen3 0.6B",
      size: "0.6B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "nano",
    },
    {
      model: "Qwen3 1.7B",
      size: "1.7B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "nano",
    },
    {
      model: "Qwen3 4B",
      size: "4B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "efficient",
    },
    {
      model: "Qwen3 8B",
      size: "8B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "open-source",
    },
    {
      model: "Qwen3 14B",
      size: "14B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "open-source",
    },
    {
      model: "Qwen3 32B",
      size: "32B",
      ctx: "128K",
      date: "2025-05-10",
      tier: "open-source",
    },
    {
      model: "Qwen3 30B-A3B (MoE)",
      size: "30B total / 3B active",
      ctx: "128K",
      date: "2025-05-10",
      tier: "efficient",
    },
    {
      model: "Qwen3 235B-A22B (MoE)",
      size: "235B total / 22B active",
      ctx: "128K",
      date: "2025-05-10",
      tier: "frontier",
    },
    {
      model: "Qwen3-Coder",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-07-22",
      tier: "coding",
    },
    {
      model: "Qwen3-Next",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-09-11",
      tier: "efficient",
    },
    {
      model: "Qwen3-Omni",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-09-23",
      tier: "multimodal",
    },
    {
      model: "Qwen3-TTS",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-12-07",
      tier: "audio",
    },
    {
      model: "Qwen3.5-9B",
      size: "9B",
      ctx: "128K",
      date: "2026-03-03",
      tier: "open-source",
    },
  ],
  "Moonshot — Kimi": [
    {
      model: "Kimi k1.5",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-01-20",
      tier: "reasoning",
    },
    {
      model: "Kimi VL",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-02-25",
      tier: "multimodal",
    },
    {
      model: "Kimi K2",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-07-17",
      tier: "open-source",
    },
    {
      model: "Kimi K2 (OK Computer)",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-09-26",
      tier: "agent",
    },
    {
      model: "Kimi K2.5",
      size: "Undisclosed",
      ctx: "128K",
      date: "2026-01-27",
      tier: "multimodal",
    },
    {
      model: "Kimi Code",
      size: "Undisclosed",
      ctx: "128K",
      date: "2026-01-27",
      tier: "coding",
    },
    {
      model: "Kimi Claw (OpenClaw)",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2026-02-16",
      tier: "agent",
    },
  ],
  "Nvidia — Models": [
    {
      model: "Nemotron-4 15B",
      size: "15B",
      ctx: "4K",
      date: "2024-03-14",
      tier: "open-source",
    },
    {
      model: "Nemotron-4 340B",
      size: "340B",
      ctx: "4K",
      date: "2024-06-14",
      tier: "open-source",
    },
    {
      model: "Llama 3.1 Nemotron 70B",
      size: "70B",
      ctx: "128K",
      date: "2024-10-03",
      tier: "open-source",
    },
    {
      model: "AceReason 7B",
      size: "7B",
      ctx: "32K",
      date: "2025-05-01",
      tier: "reasoning",
    },
    {
      model: "Nemotron 3",
      size: "Undisclosed",
      ctx: "128K",
      date: "2025-12-15",
      tier: "multi-agent",
    },
  ],
  "Microsoft — Phi (Small Language Models)": [
    {
      model: "Phi-3 Mini 3.8B",
      size: "3.8B",
      ctx: "4K/128K",
      date: "2024-04-23",
      tier: "small",
    },
    {
      model: "Phi-3 Small 7B",
      size: "7B",
      ctx: "8K/128K",
      date: "2024-04-23",
      tier: "small",
    },
    {
      model: "Phi-3 Medium 14B",
      size: "14B",
      ctx: "4K/128K",
      date: "2024-04-23",
      tier: "small",
    },
    {
      model: "Phi-3.5 Mini 3.8B",
      size: "3.8B",
      ctx: "128K",
      date: "2024-08-20",
      tier: "small",
    },
    {
      model: "Phi-3.5 MoE 16x3.8B",
      size: "42B total / 6.6B active",
      ctx: "128K",
      date: "2024-08-20",
      tier: "efficient",
    },
    {
      model: "Phi-4 14B",
      size: "14B",
      ctx: "16K",
      date: "2024-12-12",
      tier: "small",
    },
    {
      model: "Phi-4 Mini 3.8B",
      size: "3.8B",
      ctx: "128K",
      date: "2025-03-25",
      tier: "nano",
    },
    {
      model: "Phi-4 Multimodal",
      size: "~5B (est.)",
      ctx: "128K",
      date: "2025-02-25",
      tier: "multimodal",
    },
  ],
  "Amazon — Nova": [
    {
      model: "Amazon Nova Micro",
      size: "Undisclosed (<10B est.)",
      ctx: "128K",
      date: "2024-12-02",
      tier: "nano",
    },
    {
      model: "Amazon Nova Lite",
      size: "Undisclosed (~20B est.)",
      ctx: "300K",
      date: "2024-12-02",
      tier: "efficient",
    },
    {
      model: "Amazon Nova Pro",
      size: "Undisclosed",
      ctx: "300K",
      date: "2024-12-02",
      tier: "frontier",
    },
    {
      model: "Amazon Nova Premier",
      size: "Undisclosed",
      ctx: "1M",
      date: "2025-04-01",
      tier: "frontier",
    },
  ],
  "Image Generation Models": [
    {
      model: "Stable Diffusion 3 Medium",
      size: "2B",
      ctx: "N/A",
      date: "2024-06-12",
      tier: "image",
    },
    {
      model: "Stable Diffusion 3.5 Large",
      size: "8B",
      ctx: "N/A",
      date: "2024-10-22",
      tier: "image",
    },
    {
      model: "Stable Diffusion 3.5 Medium",
      size: "2.5B",
      ctx: "N/A",
      date: "2024-10-22",
      tier: "image",
    },
    {
      model: "Stable Diffusion 3.5 Large Turbo",
      size: "8B",
      ctx: "N/A",
      date: "2024-10-22",
      tier: "image",
    },
    {
      model: "FLUX.1 Dev",
      size: "12B",
      ctx: "N/A",
      date: "2024-08-01",
      tier: "image",
    },
    {
      model: "FLUX.1 Schnell",
      size: "12B",
      ctx: "N/A",
      date: "2024-08-01",
      tier: "image",
    },
    {
      model: "FLUX.1 Pro",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-08-01",
      tier: "image",
    },
    {
      model: "FLUX 1.1 Pro",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-10-01",
      tier: "image",
    },
  ],
  "Video Generation Models": [
    {
      model: "Sora",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-12-09",
      tier: "video",
    },
    {
      model: "Veo 2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-12-16",
      tier: "video",
    },
    {
      model: "Veo 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-05-20",
      tier: "video",
    },
    {
      model: "Kling 1.5",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-11-01",
      tier: "video",
    },
    {
      model: "CogVideoX 5B",
      size: "5B",
      ctx: "N/A",
      date: "2024-08-06",
      tier: "video",
    },
    {
      model: "HunyuanVideo",
      size: "13B",
      ctx: "N/A",
      date: "2024-12-03",
      tier: "video",
    },
    {
      model: "LTX-Video",
      size: "2B",
      ctx: "N/A",
      date: "2024-11-01",
      tier: "video",
    },
    {
      model: "Wan 2.1",
      size: "14B",
      ctx: "N/A",
      date: "2025-02-01",
      tier: "video",
    },
    {
      model: "SkyReels V2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-05-01",
      tier: "video",
    },
    {
      model: "Sora 2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-10-01",
      tier: "video",
    },
  ],
  "Audio / TTS Models": [
    {
      model: "Whisper Large v3",
      size: "1.5B",
      ctx: "N/A",
      date: "2023-11-01",
      tier: "audio",
    },
    {
      model: "Whisper Large v3 Turbo",
      size: "809M",
      ctx: "N/A",
      date: "2024-09-05",
      tier: "audio",
    },
    {
      model: "ElevenLabs v2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-05-01",
      tier: "audio",
    },
    {
      model: "ElevenLabs v3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2026-02-03",
      tier: "audio",
    },
    {
      model: "Qwen3-TTS",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-12-07",
      tier: "audio",
    },
    {
      model: "Suno v3.5",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-09-01",
      tier: "music",
    },
    {
      model: "Udio (MusicAI)",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-04-10",
      tier: "music",
    },
  ],
  "Specialist / Science Models": [
    {
      model: "AlphaFold 3",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-05-08",
      tier: "science",
    },
    {
      model: "AlphaGeometry 2",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-01-17",
      tier: "science",
    },
    {
      model: "AlphaProof",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2024-07-25",
      tier: "science",
    },
    {
      model: "MedGemma 4B",
      size: "4B",
      ctx: "8K",
      date: "2026-01-14",
      tier: "medical",
    },
    {
      model: "SAM 2",
      size: "~312M-641M",
      ctx: "N/A",
      date: "2024-07-29",
      tier: "vision",
    },
    {
      model: "Apple OpenELM 1.1B",
      size: "1.1B",
      ctx: "2K",
      date: "2024-04-24",
      tier: "edge",
    },
    {
      model: "Apple 3B on-device",
      size: "3B",
      ctx: "4K",
      date: "2025-06-09",
      tier: "edge",
    },
    {
      model: "OLMo 2 7B",
      size: "7B",
      ctx: "4K",
      date: "2024-11-19",
      tier: "open-source",
    },
    {
      model: "OLMo 2 13B",
      size: "13B",
      ctx: "4K",
      date: "2024-11-19",
      tier: "open-source",
    },
    {
      model: "Molmo 7B",
      size: "7B",
      ctx: "N/A",
      date: "2024-09-26",
      tier: "multimodal",
    },
    {
      model: "SmolLM 1.7B",
      size: "1.7B",
      ctx: "2K",
      date: "2024-07-17",
      tier: "edge",
    },
    {
      model: "SmolVLM 2B",
      size: "2B",
      ctx: "8K",
      date: "2024-12-11",
      tier: "multimodal",
    },
    {
      model: "IBM Granite 3.0 8B",
      size: "8B",
      ctx: "128K",
      date: "2024-10-22",
      tier: "open-source",
    },
    {
      model: "IBM Granite 3.0 2B",
      size: "2B",
      ctx: "128K",
      date: "2024-10-22",
      tier: "open-source",
    },
    {
      model: "Zamba2-7B",
      size: "7B",
      ctx: "4K",
      date: "2024-10-15",
      tier: "hybrid",
    },
    {
      model: "Cohere Command R+",
      size: "~104B",
      ctx: "128K",
      date: "2024-04-04",
      tier: "frontier",
    },
    {
      model: "Cohere Command A",
      size: "Undisclosed",
      ctx: "256K",
      date: "2025-03-13",
      tier: "frontier",
    },
    {
      model: "Cohere Aya 23-8B",
      size: "8B",
      ctx: "8K",
      date: "2024-05-23",
      tier: "multilingual",
    },
    {
      model: "Cohere Aya 23-35B",
      size: "35B",
      ctx: "8K",
      date: "2024-05-23",
      tier: "multilingual",
    },
    {
      model: "Cohere Aya Expanse 8B",
      size: "8B",
      ctx: "8K",
      date: "2024-10-22",
      tier: "multilingual",
    },
    {
      model: "Cohere Aya Expanse 32B",
      size: "32B",
      ctx: "8K",
      date: "2024-10-22",
      tier: "multilingual",
    },
    {
      model: "Falcon 180B",
      size: "180B",
      ctx: "4K",
      date: "2023-09-06",
      tier: "open-source",
    },
    {
      model: "Yi 1.5 9B",
      size: "9B",
      ctx: "4K",
      date: "2024-05-13",
      tier: "open-source",
    },
    {
      model: "Yi 1.5 34B",
      size: "34B",
      ctx: "4K",
      date: "2024-05-13",
      tier: "open-source",
    },
    {
      model: "Reka Core",
      size: "~67B (est.)",
      ctx: "128K",
      date: "2024-04-15",
      tier: "frontier",
    },
    {
      model: "Reka Flash",
      size: "~21B (est.)",
      ctx: "128K",
      date: "2024-04-15",
      tier: "efficient",
    },
    {
      model: "Perplexity Sonar Small",
      size: "~8B",
      ctx: "28K",
      date: "2024-12-01",
      tier: "efficient",
    },
    {
      model: "Perplexity Sonar Large",
      size: "~70B",
      ctx: "128K",
      date: "2024-12-01",
      tier: "frontier",
    },
    {
      model: "Amazon Alexa+",
      size: "Undisclosed",
      ctx: "N/A",
      date: "2025-02-26",
      tier: "agent",
    },
    {
      model: "Z.ai GLM-OCR 0.9B",
      size: "0.9B",
      ctx: "8K",
      date: "2026-02-03",
      tier: "specialized",
    },
  ],
};

export const PROVIDER_MAP = {
  "OpenAI — GPT Series": { p: "OpenAI", color: "#10a37f" },
  "OpenAI — o-series (Reasoning)": { p: "OpenAI", color: "#10a37f" },
  "OpenAI — Media": { p: "OpenAI", color: "#10a37f" },
  "Anthropic — Claude 3 Family": { p: "Anthropic", color: "#c77c2c" },
  "Anthropic — Claude 3.5 Family": { p: "Anthropic", color: "#c77c2c" },
  "Anthropic — Claude 3.7+": { p: "Anthropic", color: "#c77c2c" },
  "Google — Gemini": { p: "Google", color: "#1a73e8" },
  "Google — Gemma (Open-Source)": { p: "Google", color: "#1a73e8" },
  "Google — Media & Science": { p: "Google", color: "#1a73e8" },
  "Meta — Llama 3 Family": { p: "Meta", color: "#0866ff" },
  "Meta — Llama 4 Family": { p: "Meta", color: "#0866ff" },
  "Mistral AI — All Models": { p: "Mistral AI", color: "#e8520b" },
  "xAI — Grok": { p: "xAI", color: "#111" },
  "DeepSeek — All Models": { p: "DeepSeek", color: "#5b5fc7" },
  "Alibaba — Qwen2 Family": { p: "Alibaba", color: "#e04b00" },
  "Alibaba — Qwen2.5 Family": { p: "Alibaba", color: "#e04b00" },
  "Alibaba — Qwen3 Family": { p: "Alibaba", color: "#e04b00" },
  "Moonshot — Kimi": { p: "Moonshot", color: "#6d28d9" },
  "Nvidia — Models": { p: "Nvidia", color: "#76b900" },
  "Microsoft — Phi (Small Language Models)": {
    p: "Microsoft",
    color: "#00a3d1",
  },
  "Amazon — Nova": { p: "Amazon", color: "#e08a00" },
  "Image Generation Models": { p: "Various", color: "#8b5cf6" },
  "Video Generation Models": { p: "Various", color: "#d97706" },
  "Audio / TTS Models": { p: "Various", color: "#ec4899" },
  "Specialist / Science Models": { p: "Various", color: "#64748b" },
};

export const TIER_CLASS = {
  frontier: "tier-frontier",
  reasoning: "tier-reasoning",
  efficient: "tier-efficient",
  "open-source": "tier-open-source",
  coding: "tier-coding",
  nano: "tier-nano",
  edge: "tier-edge",
  small: "tier-small",
  multimodal: "tier-multimodal",
  video: "tier-video",
  image: "tier-image",
  audio: "tier-audio",
  agent: "tier-agent",
  "coding-agent": "tier-coding-agent",
  balanced: "tier-balanced",
  "reasoning-efficient": "tier-reasoning",
  "reasoning-multimodal": "tier-reasoning",
  math: "tier-coding",
  multilingual: "tier-open-source",
  privacy: "tier-balanced",
  medical: "tier-balanced",
  science: "tier-balanced",
  hybrid: "tier-balanced",
  specialized: "tier-nano",
  music: "tier-audio",
  "multi-agent": "tier-agent",
  platform: "tier-balanced",
};

// Flat list of all models for timeline and charts
export const ALL_FLAT = [];
for (const [fam, mods] of Object.entries(FAMILIES)) {
  const pm = PROVIDER_MAP[fam] || { p: "Other", color: "#94a3b8" };
  mods.forEach((m) =>
    ALL_FLAT.push({ ...m, family: fam, provider: pm.p, color: pm.color }),
  );
}
ALL_FLAT.sort((a, b) => a.date.localeCompare(b.date));

export function getTierClass(t) {
  return TIER_CLASS[t] || "tier-balanced";
}
